export default {
  enter_date: 'Datum prijave',
  birth_date: 'Datum rođenja',
  program: 'Program',
  sponsor_id: 'Sponzor',
  destination_id: 'Destinacija',
  id_number: 'Broj dokumenta',
  id_start_date: 'Datum izdavanja',
  id_end_date: 'Datum isteka',
  country: 'Država',
  city: 'Grad',
  skype: { worktravel: 'Skype', aupair: 'Kontakt za hitni slučaj' },
  postal_code: 'Poštanski broj',
  street_address: 'Adresa stanovanja',
  home_number: 'Kućni broj',
  university: 'Fakultet',
  university_program: 'Program',
  university_year: 'Godina studija',
  university_course: 'Smjer',
  university_start_date: { worktravel: 'Početak studija', aupair: 'Datum odlaska'},
  university_end_date: { worktravel: 'Završetak studija', aupair: 'Datum povratka'},
  languages: 'Strani jezik',
  health: 'Zdravlje',
  // user_id: 1,
}
